src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA1996-MAIN/integration.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-BMS(CLT)/integration_2018.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-BMS(CLT)/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-DPP/integration_2018.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-DPP/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-ECH/integration_2018.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-LDH/integration_2018.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-LDH/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-MAIN/integration_2018.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-MAIN/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-PHARM/integration_2018.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-PHARM/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2019-NIEC/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-CET2019-PDPMAIN/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-CET2019-PTDMAIN/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-CET2019-SDCGN/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/NP-CET2019-SDPCN/integration_2019.spec.js, src/components/CertificateTemplates/tlds/sg/edu/np/common/certificate.js, src/components/CertificateTemplates/tlds/sg/edu/np/common/functions.js
name: fix the display of month of certificate issuing date (full spelling with proper case)
about: The month of certificate issuing date should be full spelling with proper case while other dates in transcript should have a full spelling of month in upper case.
title: 
assignees: ''
---
=> [fix] the display of month of certificate issuing date (full spelling with proper case)

src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-002/certificate.js, src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/common/functions.js
=> UI changes in FQ-001 and FQ002

src/components/CertificateTemplates/tlds/sg/edu/rp/common/transcript.js
---
assignees: ''
---
- [X ] Did not modify any files outside of your organisation's template folder (e.g package-lock.json or anything else)
- [X ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)
=> fix GPA display

.gitignore, src/components/DecentralisedTemplateRenderer/DecentralisedRenderer.js
Provide raw document to decentralized renderer.
We need it for acra so that acra renderer can perform extra check regarding the target hash of the document
=> feat: pass down raw document to decentralized renderer

src/components/MultiTabs.js
=> fix: #466 - trigger template update when clicking on mobile tab

pages/viewer.js, src/components/CertificateViewer.js, src/components/DecentralisedTemplateRenderer/DecentralisedRenderer.js, src/components/DecentralisedTemplateRenderer/decentralisedRenderer.scss, src/components/Layout/NavigationBar/navBar.scss, src/components/Layout/footer.scss, src/components/PrintWatermark.js, src/components/certificateViewer.scss, src/styles/_variables.scss, static/style.css
For the moment if someone print using normal way (browser) then we will face the initial issue (print behaviour is 🥺). Some cases:
- user use a shortcut (https://github.com/OpenCerts/opencerts-website/issues/446) -> it's doable even though not that trivial (also need to take care of Mac user)
- user use browser menu (can't catch)
- user use contextual menu (I'm not sure can catch but I'm sure can't catch on all browser)
- more?
So this is a generic way to solve all those issues. Can enhance with catching the shortcut later
=> wip: feat: display print help message on how to print certificate

package-lock.json, package.json, src/components/CertificateViewer.tsx, src/components/tests/download-certificate.spec.js, src/components/tests/fixture/sample-dns-verified-special-characters.json
Issue:
- When downloading an OpenCert that contains special characters e.g. `#`, the data will be disappear. Most likely cos the browser thinks it's a fragment identifier and drops everything after.
Steps to reproduce:
1. Visit https://go.jiajian.me/mrdc-cert
1. Click on the Download button
1. Open up the downloaded OpenCert, and you should see the data being cut off (the original text contained `C#` so everything after `#` is dropped)
In this MR,
- Added `encodeURIComponent` to the download link
- To test, visit [this link](https://dev.opencerts.io/?q={%22type%22:%22DOCUMENT%22,%22payload%22:{%22uri%22:%22https://raw.githubusercontent.com/OpenCerts/opencerts-website/1615ad54f6135a4ba3b92316ad6e8075042848fa/src/components/tests/fixture/sample-dns-verified-special-characters.json%22,%22perm …
=> fix: encode opencert data on download

src/components/Analytics/analytics.test.ts, src/components/Analytics/index.ts, src/components/DecentralisedTemplateRenderer/DecentralisedRenderer.tsx, src/sagas/certificate.test.ts
In light of the following pivotal stories:
- https://www.pivotaltracker.com/story/show/172668387
- https://www.pivotaltracker.com/story/show/172428443
The MR adds the following analytic:
- category: "CATEGORY"
- action: "VIEWED"
- label:
- store: document store or certificate store
- document_id: id of the document stored in document.data.id (cleaned)
- name: name of the document stored in document.data.name (cleaned)
- issued_on: name of the document stored in document.data.issuedOn (cleaned)
- issuer_name: name of the issuer, if the issuer is in registry, other the value stored in document.issuer.identityProof.location (cleaned)
- issuer_id: id of the issuer, if the issuer is in registry
the value of label is a string where each element takes the form of key:value, separated by space, …
=> feat: add some analytics :)

scripts/integration-headless.sh
Reason: There's no need to install `xdg-user-dir` as it's only for *nix-based OS, hence I added the OS check.
Recap: The `apt-get` was previously added to support the `downloads-folder` plugin for our integration test.
=> chore: check os for integration test

package.json, src/components/Analytics/analytics.test.ts, src/components/Analytics/index.ts, src/sagas/certificate.test.ts, src/sagas/certificate.ts
In this MR, we draw upon the following ideas to use Google Analytics as an error tracking tool:
- https://www.smashingmagazine.com/2011/10/improve-the-user-experience-by-tracking-errors/
- https://www.analyticsmania.com/post/tracking-errors-with-google-tag-manager/ (can explore in the future)
The idea is to store a stringified list of errors in CSV format, so that it can be processed on our Google Data Studio dashboards using calculated fields.
The following errors are sent:
- `CERTIFICATE_HASH` means the verifier could not match the calculated hash with the `targetHash`, which means the document has been tampered
- `UNISSUED_CERTIFICATE` means the store does not have a record of the `merkleRoot` i.e. the document has not been issued 
- `CERTIFICATE_STORE_NOT_FOUND` means the verifier …
=> feat: error reporting in Google Analytics

pages/index.tsx, src/components/tests/load-action-encrypted-certificate.spec.js, src/reducers/certificate.actions.ts, src/sagas/certificate.ts
In order to keep secrets on the client side, this PR adds the ability to obtain the `key` from the anchor in URLs.
The verifier will now attempt to extract the `key` in the following order:
1. Anchor: `Anchor.key`
2. Query params: `Action.payload.key`
For future extensibility, `Anchor` is an object that will be safely encoded and appended as a string in the URL:
```javascript
{
key?: string;
}
```
```text
https://www.opencerts.io/verify?q={"query":"params"}#{"key":"secret"}
https://www.opencerts.io/verify?q=%7B%22query%22%3A%22params%22%7D%23%7B%22key%22%3A%22secret%22%7D
```
=> feat: obtain key from anchor

public/static/registry.json
Full name of SCIS should be: "Singapore Management University School of **Computing and** Information Systems"
=> fix: smu scis full name

next-env.d.ts, next.config.js, src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.tsx, src/components/CertificateVerifyBlock/CertificateVerifyBlock.tsx
**What does this PR do?**
- Allow trusted issuer to have their name shown alongside issuer domain
- Trusted TLDs: `*.gov.sg` and `*.edu.sg`
- Example:
```text
Certificate issued by
NTU.EDU.SG
NANYANG TECHNOLOGICAL UNIVERSITY
```
| Before | After |
|---|---|
| ![Screenshot 2022-03-07 at 2 54 06 PM](https://user-images.githubusercontent.com/37650399/156982643-ca0e49f6-0907-4d83-9b16-1be4c87e75cc.png) | ![Screenshot 2022-03-07 at 2 54 15 PM](https://user-images.githubusercontent.com/37650399/156982671-e93efe20-f538-4c4d-a5eb-8c6cf6af60ba.png) |
=> chore: show trusted issuer name alongside issuer domain

src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.tsx, src/components/CertificateVerifyBlock/CertificateVerifyBlock.tsx
**What does this PR do?**
- To have consistent behaviour as #667
- I.e. show issuer domain and name for documents issued by **trusted TLDs** and **issuers in the registry**
=> chore: show domain for documents issued by issuers in the registry

public/static/registry.json
**What this PR does:**
- Add 2 new Goerli document store addresses into registry.json
=> chore: add opencerts and tradetrust goerli addr

pages/_document.tsx, src/components/FAQ/FaqContent.tsx, src/components/HomePageContent/AboutSection.tsx, src/components/HomePageContent/DropZoneSection.tsx, src/components/Layout/FooterBar.tsx, src/components/Layout/NavigationBar/NavigationBar.tsx, src/components/Privacy/PrivacyContent.tsx, src/components/TermsOfUse/TermsOfUseContent.tsx, src/components/UI/Card/card.tsx, src/components/UI/Hero/Hero.tsx, src/components/UI/RegistryCard/RegistryCard.tsx, tailwind.config.js
SOE was encountering some rendering issues with the `Montserrat` font
- [Doesn't work] ~~Try to import Google Fonts using the recommended way: https://fonts.google.com/share?selection.family=Montserrat%7CSource%20Sans%20Pro~~
- Switch to use Poppins font for headings
=> fix: use poppins font for headings

public/static/registry.json
Add Singapore Examinations and Assessment Board (SEAB) Goerli document store address into the registry
=> chore: add seab (goerli) into registry

public/static/registry.json
Add Singapore Management University (SMU) Goerli document store address into the registry
=> chore: add smu (goerli) into registry

public/static/registry.json
Add Singapore Polytechnic (SP) Goerli document store address into the registry
=> chore: add sp (goerli) into registry

public/static/registry.json
- Add new Goerli document store address into the registry for Nanyang Polytechnic
=> chore: add Goerli address for Nanyang Polytechnic

public/static/registry.json
- Removed duplicated key ID of NYP's deprecated Ropsten document store to prevent fetching wrong data from registry
=> chore: remove NYP Ropsten document store address

public/static/registry.json
- To add in the Sepolia address so that `opencerts-function` and related repos' test files will show that the address is a valid `OpencertsRegistryVerifier` 
- Snippet of how a part of the result of the OpenCerts verification should look like after the change:
```
{
type: "ISSUER_IDENTITY",
name: "OpencertsRegistryVerifier",
status: "VALID",
data: [
{
status: "VALID",
value: "0x80ca96D2Aab5E1E23876a4D8140Ee1292327a4cd",
name: "SEPOLIA: Government Technology Agency of Singapore (GovTech)",
displayCard: false
}
]
}
...
```
- Add in Sepolia address `0x80ca96D2Aab5E1E23876a4D8140Ee1292327a4cd` into `registry.json`
=> feat: add Sepolia address

src/services/fragment.ts
For DID-signed certificates that utilises an OCSP Responder, the verifier throws a generic error message (`Whoops! It's not you, it's us`) instead of a revoked message (`Certificate has been revoked`)
- Update `certificateRevoked()` checks to also include fragments from DID-signed documents
- Check against `revokedOnAny === true` for a catch all solution
- For a stricter check, can refer to [Verify's implementation](https://github.com/Open-Attestation/verify.gov.sg/blob/e2b520dedb7dc2bb2e648a112827017b5a3fdea8/components/verify/Verifier.tsx#L78-L81)
- tl;dr Not straight forward to check `reason.code` as OCSP Revocation uses [reason codes as the revocation reason](https://github.com/Open-Attestation/ocsp-responder#reasoncode) (not to be confused with [OA status …
=> fix: check revocation status of did signed documents

public/static/registry.json
- Adds TradeTrust Sepolia document store address which is used in some tests
=> chore: add TradeTrust Sepolia addr into registry

public/static/registry.json
- Removed RP Ropsten address from into registry because its the same key as Sepolia 
- Added RP Sepolia address into registry
=> chore: add rp sepolia address

src/components/UI/Card/card.tsx
- Icons in collaborate page are being constricted
- Remove width restriction on icons in the collaborate page
=> fix: remove width restriction on icon

next.config.js, src/components/Analytics/wogaa.tsx
`process.env.NODE_ENV` cannot be overwritten
=> fix: use dedicated WOGAA_ENV env var instead

pages/_document.tsx, pages/index.tsx, src/components/Analytics/wogaa.tsx, src/components/Layout/Body.tsx
URL params and fragments may contain sensitive data that should not be sent to wooga
1. Remove including of woooga script tag in all page server side renders
2. Loading of script done on client side
3. Scrub url on verify (main page) before loading wogaa
4. Allow wogaa transactions to be buffered before the script is loaded
=> fix: scrub url before loading woogaa

pages/index.tsx, src/components/CertificateDropZone/Views/DefaultView.tsx, src/components/CertificateDropZone/Views/RetrievalErrorView.tsx, src/components/CertificateDropZone/Views/UnverifiedView.tsx, src/components/CertificateShareLink/CertificateShareLinkForm.tsx, src/components/Layout/Body.tsx, src/components/tests/dns-verified.spec.js, src/components/tests/unverified-issuer.spec.js, src/sagas/sagatests/integration-contract-not-found.spec.js, src/sagas/sagatests/integration-invalidstore.spec.js, src/sagas/sagatests/integration-merkle.spec.js, src/sagas/sagatests/integration-multiple-invalidstore.spec.js, src/sagas/sagatests/integration-tampered.spec.js, src/sagas/sagatests/integration-unissued.spec.js
Previous pr scrubbed the url before loading wogaa, but did not use the scrubbed query params for universal action.
1. move scrubbing and loading of wogaa based on scrubbing into verify page
2. update to use scrubbed `urlParams` instead of reading from next `router`
=> fix: did not use scrubbed query params

.circleci/config.yml, src/components/tests/did-dns-verified.spec.js, src/components/tests/dns-registry-verified.spec.js, src/components/tests/dns-verified.spec.js, src/components/tests/download-certificate.spec.js, src/components/tests/load-action-encrypted-certificate.spec.js, src/components/tests/load-action-plain-certificate.spec.js, src/components/tests/multi-dns-verified-certificate-store.spec.js, src/components/tests/multi-dns-verified.spec.js, src/components/tests/multi-registry-verified.spec.js, src/components/tests/obfuscated-document-verified.spec.js, src/components/tests/registry-verified.spec.js, src/components/tests/unverified-issuer.spec.js, src/components/tests/utils.js, src/components/tests/verified-unverified-issuer.spec.js, src/integration/v4/v4-verified.spec.js, src/sagas/sagatests/integration-alternate-network.spec.js, src/sagas/sagatests/integration-contract-not-found.spec.js, src/sagas/sagatests/integration-invalidstore.spec.js, src/sagas/sagatests/integration-merkle.spec.js, src/sagas/sagatests/integration-multiple-invalidstore.spec.js, src/sagas/sagatests/integration-server-error.spec.js, src/sagas/sagatests/integration-tampered.spec.js, src/sagas/sagatests/integration-unissued.spec.js
1. Flaky tests seemingly due to rate limiting by our RPC endpoints
1. added wait time before each of the test that would call the rpc
2. abstract out `validateTextContent`
3. adding npm deps caching in ci
4. only install chrome browser in ci
=> chore: improve tests

package-lock.json, package.json, src/components/tests/load-action-encrypted-certificate.spec.js, src/components/tests/load-action-plain-certificate.spec.js, src/sagas/certificate.ts, src/shared.ts
- Conditional checking for whether OA decryption is needed is [too loose on OpenCerts website](https://github.com/OpenCerts/opencerts-website/blob/95174309aa7d0f9dacd8133361020da7c726074a/src/sagas/certificate.ts#L290)
- OA v4.0 documents has a `type` property
This results in the following error as it thinks a fetched OA v4.0 document is encrypted and fails to decrypt it:
Create a stricter type guard with Zod to check whether certificate is encrypted
=> fix: hosted doc decryption

src/components/Layout/FooterBar.tsx
Rename the "Feedback" link to "Technical Query" to more accurately represent what the form is for
=> fix: rename to technical query

src/services/failover-provider.ts
- `OAFailoverProvider` is designed to retry on another provider upon an error (e.g. to accommodate situations where an Ethereum provider is down)
- [`oa-verify` library has a function](https://github.com/Open-Attestation/oa-verify/blob/b4e30a5def70124ef668ba0feff3d8298ed37e5b/src/common/utils.ts#L237-L244) that checks `isBatchableDocumentStore()`. Function is expected to throw an error if it does not support interface `0xdcfd0745`
- This inadvertently causes verifications to be a bit slower as it will always retry and exhaust all the available Ethereum providers
- Avoid retries if the function selector inside calldata is `"supportsInterface(bytes4)"`
=> fix: avoid unnecessary retries if call selector is "supportsInterface(bytes4)"
