src/components/CertificateDropZone/Views/DefaultView.js, src/components/CertificateTemplates/Default/index.js, src/components/CertificateTemplates/NgeeAnnPolytechnic/index.js, src/components/CertificateViewer.js, src/components/HomePageContent/AboutSection.js, src/components/HomePageContent/DropZoneSection.js, src/components/InvalidCertificateNotice.js, src/components/MultiCertificateRenderer.js
- Added whitelist into template index.js
- Fixed warnings with content
- Added InvalidCertificateNotice (when template is used illegally)
=> Whitelist addresses for templates

.babelrc, .eslintignore, .travis.yml, jest.config.js, jest.setup.js, package.json, src/utils/index.test.js, yarn.lock
=> added test framework

src/components/CertificateTemplates/NgeeAnnPolytechnic/NP-AA2018-DPP/transcript.js, src/components/CertificateTemplates/NgeeAnnPolytechnic/common/transcript.js
Previously the template were using standard component from the common folder but the rendering method is different for DPP transcripts.
Original version deployed submitted by NP: https://app.netlify.com/sites/opencerts-development/deploys/5beea0ede47085647b376803
=> Fixed DPP styles according tooriginals

package-lock.json, package.json
=> changed numbers to words lib to the right one

src/components/CertificateTemplates/tlds/sg/gov/seab/common/explnotes_o.js, src/components/CertificateTemplates/tlds/sg/gov/seab/common/function.js
=> SEAB - GCEO - 20190426

src/components/Privacy/privacy.scss, src/components/TermsOfUse/termsOfUse.scss
Fix: Nest the global selectors in privacy.scss under a custom class
=> Bug(CSS): Privacy.scss styles overriding global selectors

src/components/Collaborate/collaborators.json
Changed description and name
---
assignees: ''
---
=> Update NextID write up in collaborators.json

CREDITS.md
=> chore: added credits

src/components/CertificateDropZone/CertificateDropZone.js, src/components/CertificateDropZone/Views/UnverifiedView.js, src/components/tests/unverified-issuer.spec.js, src/sagas/certificate.js, src/sagas/sagatests/integration-unissued.spec.js
- Added check for issuer identity to show error when issuers unverified
=> fix error view when there is unverified issuers

package-lock.json, package.json
=> Upgraded lodash version

static/registry.json
=> Added SUSS Ropsten

next.config.js, pages/collaborators-terms.js, src/components/Collaborate/CollaboratorsTerms.js, src/components/Collaborate/CollaboratorsTerms.scss, src/components/TermsOfUse/TermsOfUseContent.js
=> feat: update terms of use

package-lock.json, package.json, src/components/CertificateViewer.js, src/components/DecentralisedTemplateRenderer/DecentralisedRenderer.js
Check #441 to see the difference in behavior with demo certificate when printing (try with background graphics).
Please also note that if the renderer can't print itself, it will default to app printing => try it out with TT demo document.
=> feat: print from frame if available

static/registry.json
---
name: Update registry for SP
about: Added SP in the registry
title: "Update registry for SP"
labels: modified SP registry
assignees: ''
---
=> Update registry for SP

static/registry.json
=> Update NIEC prod

static/registry.json
=> NIEC Ropsten

static/registry.json
=> NIEC Ropsten change in certstore, update email

pages/collaborators-terms.js, src/components/Collaborate/CollaboratePageContainer.js
=> feat: Collaborator text updates

static/registry.json
=> Add new Ropsten docuemnt store for NYP

src/components/Collaborate/CollaboratePageContainer.js, src/components/RegistryPageContainer.js, src/components/UI/Card/__snapshots__/card.test.js.snap, src/components/UI/Card/card.js, src/components/UI/Card/card.scss, src/components/UI/Card/card.test.js, static/registry.json
https://www.pivotaltracker.com/n/projects/2397228/stories/171743214
=> feat: group partners

src/components/Layout/FooterBar.tsx
In this MR, we add a feedback link to the footer.
https://www.pivotaltracker.com/story/show/173506592
=> feat: feedback link

src/components/HomePageContent/partnersPage.module.scss
https://www.pivotaltracker.com/n/projects/2397228/stories/174207008
=> fix: logo size

public/static/style.css, src/components/Layout/FooterBar.tsx, src/components/Layout/footer.module.scss, src/styles/_variables.scss
- footer alignments and reorganize info
=> chore: footer styling

package-lock.json, package.json, src/components/Analytics/index.ts
- related to Open-Attestation/oa-verify#122, Open-Attestation/open-attestation#128
=> fix: upgrade opencerts verify

src/components/CertificateDropZone/Views/UnverifiedView.tsx
This MR attempts to fix https://github.com/OpenCerts/opencerts-website/issues/551.
=> fix: stop file picker when clicking "What should I do?"

src/components/Collaborate/collaborators.json
update knowledge catalyst description
=> update knowledge catalyst description

jest.config.js, package-lock.json, package.json, src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.tsx, src/components/CertificateVerifyBlock/CertificateVerifyBlock.tsx
=> fix: display issuer correctly when resolved by multiple identity

src/components/CertificateVerifyBlock/CertificateVerifyBlock.tsx, src/components/Layout/Body.tsx, src/components/Layout/DropzoneViewWrapper.tsx, src/components/UI/RegistryCard/RegistryCard.tsx, src/tailwind.css
- fix flex bugs with ie
- remove some remnants bootstrap `container-fluid, row, col` classes in RegistryCard
=> fix: ie flex bugs

src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.tsx, src/components/CertificateVerifyBlock/CertificateVerifyBlock.tsx, src/components/HomePageContent/PartnersSection.tsx, src/components/Layout/FooterBar.tsx, src/components/Layout/NavigationBar/NavigationBar.tsx, src/components/tests/dns-registry-verified.spec.js, src/components/tests/dns-verified.spec.js, src/components/tests/download-certificate.spec.js, src/components/tests/load-action-encrypted-certificate.spec.js, src/components/tests/load-action-plain-certificate.spec.js, src/components/tests/multi-dns-verified-certificate-store.spec.js, src/components/tests/multi-dns-verified.spec.js, src/components/tests/multi-registry-verified.spec.js, src/components/tests/registry-verified.spec.js, src/components/tests/verified-unverified-issuer.spec.js, src/tailwind.css
- overflowing fixes in mobile in home + viewer page
- forgot to flex-shrink for header + footer for ie
previously:
=> fix: mobile overflowing

src/components/Collaborate/collaborators.json
name: Change collaborator text
about: Changed some text, added a word.
=> feat: change riverr text

package-lock.json, package.json
=> chore: add node and npm engines

src/components/Layout/FooterBar.tsx
- as discussed with barry, ok to shift hive logo over instead
=> fix: footer logos

src/components/Collaborate/collaborators.json
Changed description text for Riverr
=> Text change

src/components/Collaborate/collaborators.json
I'd like to change our company's description. Thanks.
=> Updated NextID description

public/static/registry.json, src/components/FAQ/content.tsx, src/components/RegistryPageContainer.tsx
Implemented stories:
- https://www.pivotaltracker.com/story/show/178350877
- https://www.pivotaltracker.com/story/show/178514846
- https://www.pivotaltracker.com/story/show/178702330
=> chore: June stories

src/components/Analytics/index.ts, src/components/DecentralisedTemplateRenderer/DecentralisedRenderer.tsx
**What does this PR do?**
- Trigger Google Analytics event whenever renderer timeouts
=> feat: track renderer timeouts

src/components/CertificateDropZone/CertificateDropZoneContainer.tsx
Fixing file handling error when drag and drop demo file into dropzone
=> fix: update dataTransfer file

src/components/Collaborate/collaborators.json
Request from NextID to update their collaborator profile.
Fixes #675
cc: @wmclaxton
=> chore: update nextid collaborator profile

public/static/registry.json
**What this PR does**
- Added Republic Polytechnic Goerlie Document Store address into registry.json
=> chore: add rp into registry

public/static/registry.json
Add ITE's Goerli document store into the registry
=> chore: add ite's goerli document store into registry

public/static/registry.json
- Add SEAB's Sepolia Document Store address into registry.json
=> chore: add seab (sepolia) into registry

src/components/DecentralisedTemplateRenderer/DecentralisedRenderer.tsx
In this PR:
- Add support for print all using hidden "print" tab
=> feat: add print all

public/static/registry.json
- Added NYP Sepolia address into registry (same address)
=> chore: add nyp sepolia address

public/static/registry.json
Added ITE Sepolia address into registry (same address)
=> chore: add ITE Sepolia address

public/static/registry.json
- update ITE's Sepolia document store address
=> chore: update ITE sepolia address

src/components/FAQ/content.tsx
In this PR:
- Remove last paragraph of FAQ
=> chore: update FAQ

.gitlab-ci.yml
=> internal build pipeline

public/static/registry.json
- add new SUTD Sepolia address into registry
=> chore: add SUTD sepolia address

src/components/Analytics/analytics.test.ts, src/components/Analytics/index.ts
In this PR:
- Send rendererUrl and templateName when sending events
=> chore: send rendererUrl and templateName

public/static/registry.json
- Add NP Sepolia document store address into the registry
=> chore: add NP sepolia address

package-lock.json, package.json, src/components/CertificateViewer.tsx, src/tailwind.css, tailwind.config.js
- print, email and download button is not clear and users have to guess what those buttons mean
- bump tailwind from `^1.9.6` to `^3.4.1`
- update tailwind config file following the version bump
- add text to button icons so users don't have to guess what the button is for
- update styling and responsiveness following the addition of text in the button
- remove the "share link" button
=> feat: enhance buttons

public/static/registry.json
- Add TP Sepolia document store address into the registry
=> chore: add tp sepolia address

public/static/registry.json
- add SP Sepolia document store into registry
=> chore: add SP Sepolia document store

pages/_document.tsx, src/components/Analytics/wogaa.tsx, src/components/DecentralisedTemplateRenderer/DecentralisedRenderer.tsx, src/config/index.ts
- Convert `pages/_document.tsx` from Class Component -> Functional Component
- Add Wogaa script based on `NODE_ENV` which is [automatically set by Next.js](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#good-to-know)
- Add transaction service to track verifications
=> feat: add wogaa script

package-lock.json, package.json, src/components/tests/dns-verified.spec.js, src/sagas/certificate.ts
This PR adds Ali DNS resolver so that traffic from China can fallback on.
- https://sgts.gitlab-dedicated.com/wog/gvt/gds-ace/general/dlt/galaxies-stories/trustdocs-stories/-/issues/290
=> feat: add ali dns resolver

src/components/Analytics/analytics.test.ts, src/components/Analytics/index.ts, src/components/CertificateViewer.tsx, src/components/DecentralisedTemplateRenderer/DecentralisedRenderer.tsx
Add GA tracking to the print button in the certificate viewer. 
- https://sgts.gitlab-dedicated.com/wog/gvt/gds-ace/general/dlt/galaxies-stories/trustdocs-stories/-/issues/301
=> feat: add ga for print

src/components/tests/dns-verified.spec.js, src/sagas/certificate.ts, src/utils/utils.ts
Add an OC DNS resolver to the verifier.
=> feat: add oc dns resolver

package-lock.json, package.json
To bump nextjs to address https://thehackernews.com/2025/03/critical-nextjs-vulnerability-allows.html
=> fix: nextjs cve

public/static/registry.json
SIT uses two contract addresses.
=> Update registry.json - SIT added new contract address

src/components/Collaborate/CollaboratePageContainer.tsx, src/components/Layout/FooterBar.tsx
[AC1 and AC2](https://sgts.gitlab-dedicated.com/wog/gvt/gds-ace/general/dlt/galaxies-stories/trustdocs-stories/-/issues/473)
=> chore: cleanup

src/components/Layout/Body.tsx
=> fix: add maintenance notice
